SET SERVEROUTPUT ON;
DECLARE
    LV_NAME VARCHAR2(30):= 'DINESH';
    LV_STR VARCHAR2(30);
    LV_STR1 VARCHAR2(30);
BEGIN
    FOR I IN 1 ..LENGTH(LV_NAME) LOOP
    LV_STR:= SUBSTR(LV_NAME,-I,1);
    LV_STR1:=LV_STR1||LV_STR;
    END LOOP;
    DBMS_OUTPUT.PUT_LINE(LV_STR1);
END;